name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: 'g++'

    - name: Build and test
      run: |
        make
        ./build/zengon
